### ISSUE TITLE
"Translucent" content flag makes brush non-solid

### ISSUE THREAD

**Issue by PalmliX** [Paril/ericw-tools#11]
Setting the translucent flag on a brush makes it non-solid. This flag is required in order to get glass materials in Q2RTX. Translucent also turns the brush non-solid so a 2nd clip trigger is required.

Ideal behavior would be have the brush remain solid when "translucent" is used, but could become non-solid if also using the "mist" flag in combination.

**Comment by Paril** [comment]
CONTENT_TRANSLUCENT (the content flag) is not meant to be manually set by the mapper - it's automatically set whenever any surface has TRANS33 or TRANS66 (which also switches solid into WINDOW). If the flag isn't being flipped automatically by glass, that's a different bug.

That being said, I did test windows recently because of a separate issue, and it might be related to that.

**Comment by PalmliX** [comment]
Understood. With the new compile tools I have to set TRANSLUCENT and TRANS33 or TRANS66 in order to make glass work in q2rtx, it doesn't work without translucent. I tried window, and window with translucent and neither of those work (i.e. glass is solid but not transparent).

In previous compilers I only had to set TRANS33 or TRANS66, I never used TRANSLUCENT previously.

**Comment by PalmliX** [comment]
Fixed in latest release!
